import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from "../components/Navbar/Navbar";
import Main from "../components/Main/Main";
import About from "../components/About/About";
import Skills from "../components/Skills/Skills";
import Projects from "../components/Projects/Projects";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Smrm | Front-end Developer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
    </div>
  );
};

export default Home;
