export const projectsImages = [
  {
    title: "Uptin WebRtc App",
    website: "https://www.uptin.app/",
    src: "/../public/assets/projects/uptinPic.jpg",
    tech: "React Js , Material Ui , Wazo",
    link: "/projects/uptin",
    id: 1,
    name: "uptin",
    description: "A Webrtc App for p2p and group call and chat.",
    technologies: [
      "Wazo",
      "Redux",
      "React js",
      "Cookie js",
      "OpenStreetMap",
      "Material Ui",
    ],
  },
  {
    title: "Notash Iot App",
    website: "https://www.platform.dmiot.ir/",
    src: "/../public/assets/projects/Notash.jpg",
    tech: "React Js , Material Ui , WebSocket",
    link: "/projects/notash",
    id: 2,
    name: "notash",
    description:
      "An Iot App to surveill and controll all your entities and devices.",
    technologies: [
      "Rechart",
      "Redux Thunk",
      "Redux",
      "React js",
      "Cookie js",
      "OpenStreetMap",
      "Material Ui",
      "Cypress",
      "Websocket",
      "Axios",
    ],
  },
  {
    title: "Star wars",
    website: "https://sith.vercel.app/",
    src: "/../public/assets/projects/starwars.jpg",
    tech: "Next Js , BootStrap , Content Full",
    link: "/projects/star wars",
    id: 3,
    name: "star wars",
    description:
      "a passion project for star wars fans as my first Next js  Project.",
    technologies: ["Next Js", "Bootstrap", "Content full"],
  },
  {
    title: "Movies",
    website: "https://moviemaster.vercel.app/",
    src: "/../public/assets/projects/movie.jpg",
    tech: "React Js , Ant D , Swiper",
    link: "/projects/imdb",
    id: 4,
    name: "imdb",
    description:
      "my firstever React js project as a beginer using TMDBs data base.",
    technologies: ["React Js", "Ant Design", "Swiper"],
  },
];
